# Lab2
[github link:(https://github.com/gqysmart/sage_math_practice/blob/main/notebooks/linear_algebra/Lassalle%20college/lab_2.ipynb) ](https://github.com/gqysmart/sage_math_practice/blob/main/notebooks/linear_algebra/Lassalle%20college/lab_2.ipynb)

## EX1

![ex1.1](./tmp/lab_2_ex1.1.png)

In [2]:
import numpy as np

A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]] 
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

C = [[1,0],
     [0,1],]

D = [[2],
     [3]]


In [3]:

def add_matrix(X:list, Y:list) -> list|None:
    rows_X = len(X)
    rows_Y = len(Y)
    cols_X = len(X[0])
    cols_Y = len(Y[0])

    if rows_X != rows_Y or cols_X != cols_Y:
        print("les dimensions des deux matrices doivent être égales.")
        return None

    result =[[0 for _ in range(cols_X)] for _ in range(rows_Y)]
    for i in range(rows_X):
        for j in range(cols_X):
            result[i][j] = X[i][j] + Y[i][j]
    
    return result

A_plus_B = add_matrix(A, B)
print("A + B =\n", A_plus_B)
print("np.add(A, B) =\n", np.add(A, B))

A + B =
 [[10, 10, 10], [10, 10, 10], [10, 10, 10]]
np.add(A, B) =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [4]:

def multiply_matrix(X:list, Y:list) -> list|None:
    rows_X = len(X)
    cols_X = len(X[0])
    rows_Y = len(Y)
    cols_Y = len(Y[0])      
    if cols_X != rows_Y:
        print("le nombre de colonnes de la première matrice doit être égal au nombre de lignes de la deuxième matrice.")
        return None
    result =[[0 for _ in range(cols_Y)] for _ in range(rows_X)]
    for i in range(rows_X):
        for j in range(cols_Y):
            sum =0 
            for k in range(cols_X):
                sum += X[i][k] * Y[k][j]
            result[i][j] = sum
    
    return result

AB = multiply_matrix(A, B)
print("A multiply B =\n", AB)
print("A @ B =\n", np.matmul(A, B))  


A multiply B =
 [[30, 24, 18], [84, 69, 54], [138, 114, 90]]
A @ B =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [5]:

CD = multiply_matrix(C, D)
print("C * D =\n", CD)

DC = multiply_matrix(D, C)
print("D * C =\n", DC)  




C * D =
 [[2], [3]]
le nombre de colonnes de la première matrice doit être égal au nombre de lignes de la deuxième matrice.
D * C =
 None


In [6]:
def transpose_matrix(X:list) -> list:
    result = [[0 for _ in range(len(X))] for _ in range(len(X[0]))]
    for i in range(len(X)):
        for j in range(len(X[0])):
            result[j][i] = X[i][j]
    return result

A_T = transpose_matrix(A)
print("A Transpose =\n", A_T)
print("np.transpose(A) =\n", np.transpose(A))

A Transpose =
 [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
np.transpose(A) =
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


### ![EX 1.2](./tmp/lab_2_ex1.2.png)

In [7]:
def determinant_2x2(X:list) -> float|None:
    if len(X) != 2 or len(X[0]) != 2:
        print("La matrice doit être de taille 2x2.")
        return None
    return X[0][0] * X[1][1] - X[0][1] * X[1][0]

def inverse_matrix_2x2(X:list) -> list|None:
    if determinant_2x2(X) is None:
        return None

    det = determinant_2x2(X)
    if abs(det) < 1e-10:
        print("La matrice n'est pas inversible (déterminant nul).")
        return None 
    
    return[[X[1][1] / det, -X[0][1] / det],
           [-X[1][0] / det, X[0][0] / det]]

M_1 = [[4, 7],
        [2, 6]]

matrix_1_inverse = inverse_matrix_2x2(M_1)
print("Inverse of M_1 =\n", matrix_1_inverse)

M_2 = [[2, 4],[1,2]]
matrix_2_inverse = inverse_matrix_2x2(M_2)
print("Inverse of M_2 =\n", matrix_2_inverse)

Inverse of M_1 =
 [[0.6, -0.7], [-0.2, 0.4]]
La matrice n'est pas inversible (déterminant nul).
Inverse of M_2 =
 None


## Résolution de systèmes d'Equation3x3

![EX2.1](./tmp/Lab_2_Ex2.1.png)

In [8]:

def resolve_gauss(A:list, b:list) -> list | None:
    n = len(A)
    Ab = [A[i] + b[i] for i in range(n)]
    for i in range(n):
        pivot_row = max(range(i,n), key=lambda r: abs(Ab[r][i]) )
        pivot_value = Ab[pivot_row][i]

        if abs(pivot_value) < 1e-10:
            print("Le système n'a pas de solution unique.")
            return None
        Ab[i], Ab[pivot_row] = Ab[pivot_row], Ab[i] # swap 

        for j in range(i+1, n):
            factor = Ab[j][i] / Ab[i][i]
            for k in range(i, n+1): # +1 for b
                Ab[j][k] -= factor * Ab[i][k]

    x = [[0] for _ in range(n)]

    for i in reversed(range(n)):
        sum_ax = 0
        for j in range(i+1, n):
            # be careful here, there are many data before a[i][i] in the matrix ab now is ineffective.
            sum_ax += Ab[i][j] * x[j][0]
        x[i][0] = (Ab[i][n] - sum_ax) / Ab[i][i]
    return x
        




A_Cofficient = [[1,-2,3],
                [2,1,1],
                [-3,2,-2]]
b =[[7],
    [4],
    [-10]]

x = resolve_gauss(A_Cofficient, b)
print("Solution x =\n", x)
x = np.linalg.solve(A_Cofficient, b)
print("np.linalg.solve Solution x =\n", x)


Solution x =
 [[2.0], [-0.9999999999999998], [1.0000000000000002]]
np.linalg.solve Solution x =
 [[ 2.]
 [-1.]
 [ 1.]]


![ex2.2](./tmp/Lab_2_Ex2.2.png)

In [9]:
from typing import Sequence
def determinant_3x3(A:Sequence) -> float|None:
    if len(A) != 3 or len(A[0]) != 3:
        print("La matrice doit être de taille 3x3.")
        return None
    
    det = A[0][0] * (A[1][1] * A[2][2] - A[1][2] * A[2][1]) - A[0][1] * (A[1][0] * A[2][2] - A[1][2] * A[2][0]) + A[0][2] * (A[1][0] * A[2][1] - A[1][1] * A[2][0])
    return det
        

def resolve_cramer_3x3(A:list, b:list) -> list | None:
    det_A = determinant_3x3(A)
    if det_A is None or abs(det_A) < 1e-10:
        print("Le système n'a pas de solution unique.")
        return None
    
    x = [[0] for _ in range(3)]
    for i in range(3):
        A_i = [row[:] for row in A]  # deep copy
        for j in range(3):
            A_i[j][i] = b[j][0]
        det_A_i = determinant_3x3(A_i)
        if det_A_i is None:
            return None
        x[i][0] = det_A_i / det_A

    return x

x = resolve_cramer_3x3(A_Cofficient, b)
print("Cramer's Rule Solution x =\n", x)
x = resolve_gauss(A_Cofficient, b)
print("Gauss Elimination Solution x =\n", x)
x = np.linalg.solve(A_Cofficient, b)
print("np.linalg.solve Solution x =\n", x)


Cramer's Rule Solution x =
 [[2.0], [-1.0], [1.0]]
Gauss Elimination Solution x =
 [[2.0], [-0.9999999999999998], [1.0000000000000002]]
np.linalg.solve Solution x =
 [[ 2.]
 [-1.]
 [ 1.]]


## EX3 Application réelle et modélisation

![Ex3.1](./tmp/Lab_2_Ex3.1.png)

In [13]:
P =[[2,1,3],
    [1,3,2],
    [3,2,1]]

b = [[100],
     [120],
     [140]]

n = resolve_cramer_3x3(P, b)
print("Cramer's Rule Solution n =\n", n)
n = resolve_gauss(P, b)
print("Gauss Elimination Solution n =\n", n) 
n = np.linalg.solve(P, b)
print("np.linalg.solve Solution n =\n", n)


print("Analysis:\n ces valeurs ne sont pas des entiers.\n" ,
"Comme la produition réel doit être en entier,\n",
"it n'est pas possible de produire ces quantités exactes.\n",)



Cramer's Rule Solution n =
 [[26.666666666666668], [26.666666666666668], [6.666666666666667]]
Gauss Elimination Solution n =
 [[26.666666666666668], [26.666666666666668], [6.666666666666667]]
np.linalg.solve Solution n =
 [[26.66666667]
 [26.66666667]
 [ 6.66666667]]
Analysis:
 ces valeurs ne sont pas des entiers.
 Comme la produition réel doit être en entier,
 it n'est pas possible de produire ces quantités exactes.



### ![Ex3.2](./tmp/Lab_2_Ex3.2.png)

In [17]:
def rotate_2D(point:Sequence, theta:float) -> Sequence:
    cos_theta = np.cos(theta)
    sin_theta = np.sin(theta)
    R = [[cos_theta, -sin_theta],
                       [sin_theta, cos_theta]]
    return np.matmul(R, point)

def scale_2D(point:Sequence, sx:float, sy:float) -> Sequence:
    S = [[sx, 0],
         [0, sy]]
    return np.matmul(S, point)

P = [[5],[3]]
theta = np.pi/2
print("1: P'=\n", rotate_2D(P, np.pi/4))
s_x ,s_y =2, 0.5
print("2: P''=\n", scale_2D(P, s_x, s_y))

print("3: conclusion: \n"
"L’ordre des transformations est crucial parce que la composition des matrices n’est pas commutative."," Autrement dit :\n",
"R(S · P) ≠ S(R · P)")
    

1: P'=
 [[1.41421356]
 [5.65685425]]
2: P''=
 [[10. ]
 [ 1.5]]
3: conclusion: 
L’ordre des transformations est crucial parce que la composition des matrices n’est pas commutative.  Autrement dit :
 R(S · P) ≠ S(R · P)


### ![EX4.1](./tmp/Lab_2_Ex4.1.png) ![Ex4.1-2](./tmp/Lab_2_Ex4.1_2.png)



$$
\hat{y} =
\begin{pmatrix}
1 & x
\end{pmatrix}
\begin{pmatrix}
b \\
w
\end{pmatrix}
= b + wx
$$

Cette solution est possible parce que, dans le cas d’un modèle linéaire, la fonction de perte est convexe.  Ainsi, un minimum global existe et peut être trouvé directement par un calcul matriciel.
$$
Minimize E(β)= ∥Y−Xβ∥^2=(Y-X\beta)^T(Y-X\beta)
$$

$$ 
\begin{aligned}
E(\beta)
&= (Y^T - \beta^T X^T)(Y - X\beta) \\
&= Y^T Y - Y^T X\beta - \beta^T X^T Y + \beta^T X^T X \beta
\end{aligned}
$$

$$
\frac{\partial E}{\partial \beta}
= -2 X^T Y + 2 X^T X \beta
$$

$$
-2 X^T Y + 2 X^T X \beta = 0
$$


$$
X^T X \beta = X^T Y
$$

---
$$
\beta = (X^T X)^{-1} X^T Y
$$












In [20]:
X=[[1,1],[1,2],[1,3]]
Y=[[2],[3],[4]]
X_T_X = np.matmul(np.transpose(X), X)   
Inverse_X_T_X = np.linalg.inv(X_T_X)
X_T_Y = np.matmul(np.transpose(X), Y)

X_T_Y = np.matmul(np.transpose(X), Y)

Beta = np.matmul(Inverse_X_T_X, X_T_Y)
print("Beta =\n", Beta)

print ("La drointe de régression est: y =", Beta[0][0], " + ", Beta[1][0], "x")
x = 4
print("quand x = 4, y=", Beta[0][0] + Beta[1][0] * x)

Beta =
 [[1.]
 [1.]]
La drointe de régression est: y = 0.9999999999999973  +  1.0 x
quand x = 4, y= 4.999999999999997
